version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5274:8080" 
      - "7090:8081"
    environment:
      - RabbitMQ__HostName=rabbitmq # Configuração de ambiente para o RabbitMQ
      - ASPNETCORE_ENVIRONMENT=Development #
    depends_on:
      - rabbitmq
      - docker-sqlserver
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta do RabbitMQ
      - "15672:15672" # Porta para o painel de administração
    networks:
      - app-network
  docker-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "3333:1433"
networks:
  app-network:
    driver: bridge